version: '3.8'

services:
  # MongoDB Database
  mongodb:
    image: mongo:7.0
    container_name: showcase-mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: showcase
    volumes:
      - mongodb_data:/data/db
      - ./scripts/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - showcase-network

  # Redis for BullMQ
  redis:
    image: redis:7.2-alpine
    container_name: showcase-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - showcase-network

  # MinIO for S3-compatible storage (local development)
  minio:
    image: minio/minio:latest
    container_name: showcase-minio
    restart: unless-stopped
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    networks:
      - showcase-network

  # API Backend (NestJS)
  # api:
  #   build:
  #     context: ./apps/api
  #     dockerfile: Dockerfile.dev
  #   container_name: showcase-api
  #   restart: unless-stopped
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     NODE_ENV: development
  #     MONGODB_URI: mongodb://admin:password@mongodb:27017/showcase?authSource=admin
  #     REDIS_URL: redis://redis:6379
  #     MINIO_ENDPOINT: minio
  #     MINIO_PORT: 9000
  #     MINIO_ACCESS_KEY: minioadmin
  #     MINIO_SECRET_KEY: minioadmin123
  #     MINIO_BUCKET: showcase-media
  #     JWT_SECRET: d6bU645Net8i6Abg1LOOFmEl7V8FCV5w9j/fmW1MVKg=
  #     CLERK_SECRET_KEY: sk_test_lWEJJRMIFBL0UKfRHeE0GUomgRpb1rqFOhQMxbI0pe
  #   volumes:
  #     - ./apps/api:/app
  #     - /app/node_modules
  #   depends_on:
  #     - mongodb
  #     - redis
  #     - minio
  #   networks:
  #     - showcase-network

  # # Web Frontend (Next.js)
  # web:
  #   build:
  #     context: ./apps/web
  #     dockerfile: Dockerfile.dev
  #   container_name: showcase-web
  #   restart: unless-stopped
  #   ports:
  #     - "3000:3000"
  #   environment:
  #     NODE_ENV: development
  #     NEXT_PUBLIC_API_URL: http://localhost:4000/graphql
  #     NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: pk_test_cmVmaW5lZC1zbmlwZS00Ny5jbGVyay5hY2NvdW50cy5kZXYk
  #     CLERK_SECRET_KEY: sk_test_lWEJJRMIFBL0UKfRHeE0GUomgRpb1rqFOhQMxbI0pe

  #   volumes:
  #     - ./apps/web:/app
  #     - /app/node_modules
  #     - /app/.next
  #   depends_on:
  #     - api
  #   networks:
  #     - showcase-network

volumes:
  mongodb_data:
  redis_data:
  minio_data:

networks:
  showcase-network:
    driver: bridge
