apiVersion: v1
kind: Secret
metadata:
  name: showcase-secrets
  namespace: showcase-apps
type: Opaque
data:
  # Base64 encoded values - replace with your actual values
  mongodb-uri: bW9uZ29kYjovL3VzZXI6cGFzc3dvcmRAbW9uZ29kYi5zaG93Y2FzZS1hcHBzLnN2Yy5jbHVzdGVyLmxvY2FsOjI3MDE3L3Nob3djYXNl
  redis-url: cmVkaXM6Ly9yZWRpcy5zaG93Y2FzZS1hcHBzLnN2Yy5jbHVzdGVyLmxvY2FsOjYzNzk=
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1oZXJl
  clerk-secret-key: eW91ci1jbGVyay1zZWNyZXQta2V5
  clerk-publishable-key: eW91ci1jbGVyay1wdWJsaXNoYWJsZS1rZXk=
  minio-access-key: bWluaW9hZG1pbg==
  minio-secret-key: bWluaW9hZG1pbjEyMw==
  sentry-dsn: eW91ci1zZW50cnktZHNu
  smtp-user: eW91ci1zbXRwLXVzZXI=
  smtp-pass: eW91ci1zbXRwLXBhc3N3b3Jk
  algolia-app-id: eW91ci1hbGdvbGlhLWFwcC1pZA==
  algolia-api-key: eW91ci1hbGdvbGlhLWFwaS1rZXk=
