apiVersion: apps/v1
kind: Deployment
metadata:
  name: showcase-web
  namespace: showcase-apps
  labels:
    app: showcase-web
spec:
  replicas: 3
  selector:
    matchLabels:
      app: showcase-web
  template:
    metadata:
      labels:
        app: showcase-web
    spec:
      containers:
      - name: web
        image: ghcr.io/your-org/showcase-apps/web:latest
        ports:
        - containerPort: 3000
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: NEXT_PUBLIC_API_URL
          value: "https://api.showcase-apps.com/graphql"
        - name: NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY
          valueFrom:
            secretKeyRef:
              name: showcase-secrets
              key: clerk-publishable-key
        - name: CLERK_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: showcase-secrets
              key: clerk-secret-key
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: showcase-web-service
  namespace: showcase-apps
spec:
  selector:
    app: showcase-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 3000
  type: ClusterIP
