name: Dependency Updates

on:
  schedule:
    # Run every Monday at 9 AM UTC
    - cron: '0 9 * * 1'
  workflow_dispatch:

jobs:
  update-dependencies:
    name: Update Dependencies
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Update dependencies
        run: |
          # Update root dependencies
          npm update
          
          # Update API dependencies
          cd apps/api
          npm update
          
          # Update Web dependencies
          cd ../web
          npm update
          
          # Update Mobile dependencies
          cd ../mobile
          npm update

      - name: Check for updates
        run: |
          # Check for outdated packages
          echo "Root dependencies:"
          npm outdated || true
          
          echo "API dependencies:"
          cd apps/api && npm outdated || true
          
          echo "Web dependencies:"
          cd ../web && npm outdated || true
          
          echo "Mobile dependencies:"
          cd ../mobile && npm outdated || true

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: 'chore: update dependencies'
          title: 'chore: update dependencies'
          body: |
            This PR updates dependencies across all applications.
            
            ## Changes
            - Updated root package dependencies
            - Updated API dependencies
            - Updated Web dependencies
            - Updated Mobile dependencies
            
            ## Testing
            Please review the changes and run tests to ensure everything works correctly.
          branch: dependency-updates
          delete-branch: true

  security-audit:
    name: Security Audit
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run security audit
        run: |
          # Audit root dependencies
          npm audit --audit-level moderate || true
          
          # Audit API dependencies
          cd apps/api
          npm audit --audit-level moderate || true
          
          # Audit Web dependencies
          cd ../web
          npm audit --audit-level moderate || true
          
          # Audit Mobile dependencies
          cd ../mobile
          npm audit --audit-level moderate || true

      - name: Create security issue
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'Security vulnerabilities detected',
              body: 'Security audit found vulnerabilities in dependencies. Please review and update.',
              labels: ['security', 'dependencies']
            })

  license-check:
    name: License Check
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Check licenses
        run: |
          # Install license checker
          npm install -g license-checker
          
          # Check licenses for all apps
          echo "Checking licenses..."
          license-checker --summary || true
          
          # Check for problematic licenses
          license-checker --excludePrivatePackages --onlyAllow 'MIT;Apache-2.0;BSD-2-Clause;BSD-3-Clause;ISC' || true
